[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "cryptography>=42",
    "django>=5.1,<6.0",
    "djangorestframework>=3.15",
    "grpcio>=1.83.1",
    "grpcio-tools>=1.83.1",
    "psycopg[binary]>=3.2",
    "pydantic-settings>=2.4",
    "pyyaml>=6.0.3",
]
