# Generated by Django 5.2.17 on 2026-09-04 07:52

import apps.importer.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.CharField(default=apps.importer.models.generate_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('connection_id', models.CharField(db_index=True, max_length=24)),
                ('status', models.CharField(choices=[('running', 'running'), ('completed', 'completed'), ('errored', 'errored'), ('cancelled', 'cancelled'), ('quota_exceeded', 'quota_exceeded')], default='running', max_length=16)),
                ('trigger', models.CharField(choices=[('manual', 'manual'), ('webhook', 'webhook'), ('scheduled', 'scheduled')], default='manual', max_length=16)),
                ('cursor', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('items_written', models.PositiveIntegerField(default=0)),
                ('items_failed', models.PositiveIntegerField(default=0)),
                ('bytes_written', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'db_table': 'importer_sync_run',
            },
        ),
        migrations.CreateModel(
            name='RawDocument',
            fields=[
                ('id', models.CharField(default=apps.importer.models.generate_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('connection_id', models.CharField(db_index=True, max_length=24)),
                ('provider_document_id', models.CharField(db_index=True, max_length=256)),
                ('provider_version', models.CharField(blank=True, default='', max_length=256)),
                ('payload', models.BinaryField()),
                ('content_type', models.CharField(blank=True, default='', max_length=128)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'importer_raw_document',
                'constraints': [models.UniqueConstraint(fields=('connection_id', 'provider_document_id', 'provider_version'), name='uniq_raw_document_version')],
            },
        ),
        migrations.CreateModel(
            name='SyncItemFailure',
            fields=[
                ('id', models.CharField(default=apps.importer.models.generate_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('provider_document_id', models.CharField(max_length=256)),
                ('failure_type', models.CharField(choices=[('transient_exhausted', 'transient_exhausted'), ('permanent', 'permanent'), ('auth_expired', 'auth_expired')], max_length=24)),
                ('error_message', models.TextField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failures', to='importer.syncrun')),
            ],
            options={
                'db_table': 'importer_sync_item_failure',
            },
        ),
    ]
