# Generated by Django 5.2.17 on 2026-09-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdocument',
            name='project_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=24),
        ),
    ]
