# Generated by Django 5.2.17 on 2026-09-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_rawdocument_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdocument',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
