"""Temporal activities for turning a resume into an interview.

Every activity takes and returns plain JSON-serialisable values: Temporal records their
arguments and results in workflow history, so a model instance passed across this
boundary would be a row frozen at the moment it was written.
"""

import logging

from asgiref.sync import sync_to_async
from temporalio import activity

from apps.interview import resume as resume_service
from apps.interview import round_content
from apps.interview.models import InterviewRound, InterviewSession

logger = logging.getLogger(__name__)


class SessionGone(Exception):
    """The session was deleted while its plan was being built."""


async def _session(session_id: str) -> InterviewSession:
    session = await InterviewSession.objects.filter(id=session_id).afirst()
    if session is None:
        raise SessionGone(session_id)
    return session


@activity.defn
async def parse_resume_activity(session_id: str, document_id: str) -> dict:
    parsed = await resume_service.read_and_parse(await _session(session_id), document_id)
    return parsed.as_dict()


@activity.defn
async def generate_plan_activity(session_id: str, parsed: dict) -> dict:
    """The index: one model call, then the facts and per-round summaries it produced.

    Returns what the workflow needs to describe itself -- how many probes were found and
    which rounds the plan actually spoke about -- rather than the plan itself, which is
    large and already persisted.
    """
    session = await _session(session_id)
    resume = resume_service.ParsedResume.from_dict(parsed)
    plan = await resume_service.build_plan(resume.text)
    await resume_service.persist_plan(session, resume, plan)

    planned = await sync_to_async(_planned_rounds_sync, thread_sensitive=True)(
        session_id, sorted(plan["rounds"])
    )
    return {"probe_count": len(plan["probes"]), "rounds": planned}


def _planned_rounds_sync(session_id: str, stage_ids: list[str]) -> list[dict]:
    rounds = InterviewRound.objects.filter(session_id=session_id, stage_id__in=stage_ids)
    labels = {r.stage_id: r.label for r in rounds}
    return [{"stageId": stage, "label": labels.get(stage, stage)} for stage in stage_ids]


@activity.defn
async def generate_round_content_activity(session_id: str, stage_id: str) -> bool:
    """One round's task payload. False when nothing generated it.

    False rather than an exception: a stage with no generator yet is not a failure to
    retry, and the workflow should carry on preparing the rounds that do have one.
    """
    session = await _session(session_id)
    round_ = await InterviewRound.objects.filter(session_id=session_id, stage_id=stage_id).afirst()
    if round_ is None:
        return False

    await _set_content_state(round_, InterviewRound.ContentState.GENERATING)
    try:
        content = await round_content.generate(session, stage_id)
    except Exception:
        logger.warning("Couldn't generate %s content for %s", stage_id, session_id, exc_info=True)
        await _set_content_state(round_, InterviewRound.ContentState.FAILED)
        raise

    if content is None:
        await _set_content_state(round_, InterviewRound.ContentState.PENDING)
        return False

    round_.content = content
    round_.content_state = InterviewRound.ContentState.READY
    await round_.asave(update_fields=["content", "content_state"])
    return True


async def _set_content_state(round_: InterviewRound, state: str) -> None:
    round_.content_state = state
    await round_.asave(update_fields=["content_state"])


@activity.defn
async def set_plan_state_activity(session_id: str, state: str, error: str = "") -> None:
    session = await _session(session_id)
    session.plan_state = state
    session.plan_error = error
    await session.asave(update_fields=["plan_state", "plan_error", "updated_at"])


@activity.defn
async def rounds_needing_content_activity(session_id: str, stage_ids: list[str]) -> list[dict]:
    """Which of these rounds still want generating, in the order asked for.

    Asked of the database rather than remembered in the workflow, because a round can
    also be generated by an earlier signal -- and preparing one twice means paying for
    the same model call twice.
    """
    return await sync_to_async(_rounds_needing_content_sync, thread_sensitive=True)(
        session_id, stage_ids
    )


def _rounds_needing_content_sync(session_id: str, stage_ids: list[str]) -> list[dict]:
    rounds = {
        r.stage_id: r
        for r in InterviewRound.objects.filter(session_id=session_id, stage_id__in=stage_ids)
    }
    wanted = []
    for stage in stage_ids:
        round_ = rounds.get(stage)
        if stage not in round_content.GENERATABLE_STAGE_IDS or round_ is None:
            continue
        if round_.content_state != InterviewRound.ContentState.PENDING:
            continue
        wanted.append({"stageId": stage, "label": round_.label})
    return wanted
