# Generated by Django 5.2.17 on 2026-09-26 17:51

import apps.portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.CharField(default=apps.portfolio.models.generate_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'portfolio_contact_message',
            },
        ),
        migrations.CreateModel(
            name='PortfolioQuery',
            fields=[
                ('id', models.CharField(default=apps.portfolio.models.generate_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('ask', 'ask'), ('fit', 'fit')], max_length=8)),
                ('text', models.TextField()),
                ('retrieved', models.JSONField(blank=True, default=list)),
                ('answer', models.TextField(blank=True, default='')),
                ('outcome', models.CharField(choices=[('answered', 'answered'), ('failed', 'failed')], max_length=16)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'portfolio queries',
                'db_table': 'portfolio_query',
            },
        ),
    ]
