# Generated by Django 5.2.17 on 2026-09-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioquery',
            name='kind',
            field=models.CharField(choices=[('ask', 'ask'), ('fit', 'fit'), ('voice', 'voice')], max_length=8),
        ),
    ]
