# Generated by Django 5.2.17 on 2026-09-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewround',
            name='content_state',
            field=models.CharField(choices=[('pending', 'pending'), ('generating', 'generating'), ('ready', 'ready'), ('failed', 'failed')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='plan_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='plan_state',
            field=models.CharField(choices=[('idle', 'idle'), ('processing', 'processing'), ('ready', 'ready'), ('failed', 'failed')], default='idle', max_length=16),
        ),
    ]
