# Generated by Django 5.2.17 on 2026-09-13 08:27

import apps.interview.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_interviewround_content_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeRun',
            fields=[
                ('id', models.CharField(default=apps.interview.models.generate_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('stage_id', models.CharField(max_length=32)),
                ('task_index', models.IntegerField(default=0)),
                ('language', models.CharField(max_length=16)),
                ('attempt', models.IntegerField()),
                ('files', models.JSONField(blank=True, default=dict)),
                ('phase', models.CharField(choices=[('running', 'running'), ('ran', 'ran'), ('compile_failed', 'compile_failed'), ('crashed', 'crashed'), ('timeout', 'timeout'), ('unavailable', 'unavailable')], default='running', max_length=16)),
                ('tests', models.JSONField(blank=True, default=list)),
                ('terminal', models.JSONField(blank=True, default=list)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('truncated', models.BooleanField(default=False)),
                ('timed_out', models.BooleanField(default=False)),
                ('retain_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_runs', to='interview.interviewsession')),
            ],
            options={
                'db_table': 'interview_code_run',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='CodeDraft',
            fields=[
                ('id', models.CharField(default=apps.interview.models.generate_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('stage_id', models.CharField(max_length=32)),
                ('task_index', models.IntegerField(default=0)),
                ('language', models.CharField(max_length=16)),
                ('file_name', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('retain_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='interview.interviewsession')),
            ],
            options={
                'db_table': 'interview_code_draft',
                'constraints': [models.UniqueConstraint(fields=('session', 'stage_id', 'task_index', 'language', 'file_name'), name='uniq_draft_per_file')],
            },
        ),
    ]
