# Generated by Django 5.2.17 on 2026-09-20 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_coderun_codedraft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewround',
            name='citation',
        ),
        migrations.RemoveField(
            model_name='resumefacts',
            name='citations',
        ),
    ]
