# Generated by Django 5.2.17 on 2026-09-20 11:12

import apps.interview.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_remove_interviewround_citation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewTask',
            fields=[
                ('id', models.CharField(default=apps.interview.models.generate_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('kind', models.CharField(choices=[('coding', 'coding'), ('sql', 'sql')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('languages', models.JSONField(default=list)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('licence', models.CharField(blank=True, default='', max_length=64)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interview_task',
                'indexes': [models.Index(fields=['kind', 'retired_at'], name='interview_t_kind_d3618e_idx')],
            },
        ),
    ]
