# Generated by Django 5.2.17 on 2026-09-03 14:47

import apps.tps.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.CharField(default=apps.tps.models.generate_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('app_code', models.IntegerField(unique=True)),
                ('app_name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=128)),
                ('auth_type', models.IntegerField(choices=[(1, 'oauth2'), (2, 'api_key'), (3, 'basic_auth'), (4, 'form_based_oauth2'), (5, 'mtls')])),
                ('category', models.IntegerField(choices=[(1, 'source_control'), (2, 'hosting'), (3, 'distribution'), (4, 'coming_soon')])),
                ('provider', models.IntegerField(choices=[(1, 'native')], default=1)),
                ('meta', models.JSONField(default=dict)),
                ('is_install_required', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tps_connector',
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.CharField(default=apps.tps.models.generate_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('project_id', models.CharField(db_index=True, max_length=24)),
                ('app_name', models.CharField(db_index=True, max_length=64)),
                ('config_encrypted', models.TextField()),
                ('status', models.CharField(choices=[('active', 'active'), ('revoked', 'revoked'), ('reauth_required', 'reauth_required')], default='active', max_length=16)),
                ('identifier', models.CharField(blank=True, default='', max_length=256)),
                ('expires_at', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tps.connector')),
            ],
            options={
                'db_table': 'tps_connection',
            },
        ),
    ]
