# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import tps_pb2 as tps__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tps_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TpsServiceStub:
    """tps proves a Connection has a valid, refreshable token. This is the entire
    interface anything else (apps.core) is allowed to depend on.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListApps = channel.unary_unary(
                '/tps.TpsService/ListApps',
                request_serializer=tps__pb2.ListAppsRequest.SerializeToString,
                response_deserializer=tps__pb2.ListAppsResponse.FromString,
                _registered_method=True)
        self.GetApp = channel.unary_unary(
                '/tps.TpsService/GetApp',
                request_serializer=tps__pb2.GetAppRequest.SerializeToString,
                response_deserializer=tps__pb2.App.FromString,
                _registered_method=True)
        self.InstallApp = channel.unary_unary(
                '/tps.TpsService/InstallApp',
                request_serializer=tps__pb2.InstallAppRequest.SerializeToString,
                response_deserializer=tps__pb2.InstallAppResponse.FromString,
                _registered_method=True)
        self.ExchangeCode = channel.unary_unary(
                '/tps.TpsService/ExchangeCode',
                request_serializer=tps__pb2.ExchangeCodeRequest.SerializeToString,
                response_deserializer=tps__pb2.ConnectionSummary.FromString,
                _registered_method=True)
        self.ConnectCredentials = channel.unary_unary(
                '/tps.TpsService/ConnectCredentials',
                request_serializer=tps__pb2.ConnectCredentialsRequest.SerializeToString,
                response_deserializer=tps__pb2.ConnectionSummary.FromString,
                _registered_method=True)
        self.ListConnections = channel.unary_unary(
                '/tps.TpsService/ListConnections',
                request_serializer=tps__pb2.ListConnectionsRequest.SerializeToString,
                response_deserializer=tps__pb2.ListConnectionsResponse.FromString,
                _registered_method=True)
        self.GetConnection = channel.unary_unary(
                '/tps.TpsService/GetConnection',
                request_serializer=tps__pb2.GetConnectionRequest.SerializeToString,
                response_deserializer=tps__pb2.ConnectionSummary.FromString,
                _registered_method=True)
        self.GetToken = channel.unary_unary(
                '/tps.TpsService/GetToken',
                request_serializer=tps__pb2.GetTokenRequest.SerializeToString,
                response_deserializer=tps__pb2.GetTokenResponse.FromString,
                _registered_method=True)
        self.DeleteConnection = channel.unary_unary(
                '/tps.TpsService/DeleteConnection',
                request_serializer=tps__pb2.DeleteConnectionRequest.SerializeToString,
                response_deserializer=tps__pb2.DeleteConnectionResponse.FromString,
                _registered_method=True)


class TpsServiceServicer:
    """tps proves a Connection has a valid, refreshable token. This is the entire
    interface anything else (apps.core) is allowed to depend on.
    """

    def ListApps(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetApp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InstallApp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExchangeCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectCredentials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConnections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConnection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteConnection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TpsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListApps': grpc.unary_unary_rpc_method_handler(
                    servicer.ListApps,
                    request_deserializer=tps__pb2.ListAppsRequest.FromString,
                    response_serializer=tps__pb2.ListAppsResponse.SerializeToString,
            ),
            'GetApp': grpc.unary_unary_rpc_method_handler(
                    servicer.GetApp,
                    request_deserializer=tps__pb2.GetAppRequest.FromString,
                    response_serializer=tps__pb2.App.SerializeToString,
            ),
            'InstallApp': grpc.unary_unary_rpc_method_handler(
                    servicer.InstallApp,
                    request_deserializer=tps__pb2.InstallAppRequest.FromString,
                    response_serializer=tps__pb2.InstallAppResponse.SerializeToString,
            ),
            'ExchangeCode': grpc.unary_unary_rpc_method_handler(
                    servicer.ExchangeCode,
                    request_deserializer=tps__pb2.ExchangeCodeRequest.FromString,
                    response_serializer=tps__pb2.ConnectionSummary.SerializeToString,
            ),
            'ConnectCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectCredentials,
                    request_deserializer=tps__pb2.ConnectCredentialsRequest.FromString,
                    response_serializer=tps__pb2.ConnectionSummary.SerializeToString,
            ),
            'ListConnections': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConnections,
                    request_deserializer=tps__pb2.ListConnectionsRequest.FromString,
                    response_serializer=tps__pb2.ListConnectionsResponse.SerializeToString,
            ),
            'GetConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConnection,
                    request_deserializer=tps__pb2.GetConnectionRequest.FromString,
                    response_serializer=tps__pb2.ConnectionSummary.SerializeToString,
            ),
            'GetToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GetToken,
                    request_deserializer=tps__pb2.GetTokenRequest.FromString,
                    response_serializer=tps__pb2.GetTokenResponse.SerializeToString,
            ),
            'DeleteConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteConnection,
                    request_deserializer=tps__pb2.DeleteConnectionRequest.FromString,
                    response_serializer=tps__pb2.DeleteConnectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tps.TpsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tps.TpsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TpsService:
    """tps proves a Connection has a valid, refreshable token. This is the entire
    interface anything else (apps.core) is allowed to depend on.
    """

    @staticmethod
    def ListApps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tps.TpsService/ListApps',
            tps__pb2.ListAppsRequest.SerializeToString,
            tps__pb2.ListAppsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tps.TpsService/GetApp',
            tps__pb2.GetAppRequest.SerializeToString,
            tps__pb2.App.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InstallApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tps.TpsService/InstallApp',
            tps__pb2.InstallAppRequest.SerializeToString,
            tps__pb2.InstallAppResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExchangeCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tps.TpsService/ExchangeCode',
            tps__pb2.ExchangeCodeRequest.SerializeToString,
            tps__pb2.ConnectionSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConnectCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tps.TpsService/ConnectCredentials',
            tps__pb2.ConnectCredentialsRequest.SerializeToString,
            tps__pb2.ConnectionSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListConnections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tps.TpsService/ListConnections',
            tps__pb2.ListConnectionsRequest.SerializeToString,
            tps__pb2.ListConnectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tps.TpsService/GetConnection',
            tps__pb2.GetConnectionRequest.SerializeToString,
            tps__pb2.ConnectionSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tps.TpsService/GetToken',
            tps__pb2.GetTokenRequest.SerializeToString,
            tps__pb2.GetTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tps.TpsService/DeleteConnection',
            tps__pb2.DeleteConnectionRequest.SerializeToString,
            tps__pb2.DeleteConnectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
